### ISSUE TITLE
Suggestion: mobBow

### ISSUE THREAD

**Issue by ghost** [NienteSpigotSenzaJava/UltimateBows#2]
I think a bow who spawns a random mob would be cool.

**Comment by NienteSpigotSenzaJava** [comment]
Great idea! Would you like to add it by yourself making a pull request?

(BTW, the reason why I am asking for pull requests is because I like when people contribute to my projects and I love to compare my code to other's code to learn, but if you don't have enough time don't worry, let me know and I'll add it by myself).

**Comment by ghost** [comment]
Added with #5
